### PR TITLE
Filecoin with BLS support

### PR DESCRIPTION
**Pull request by ukstv**
- Expect filecoin provider implementing WalletSubProvider from [Glif.io](https://github.com/glifio/modules)
- Support Filecoin BLS signatures
- Use Uint8Array instead of Buffer (ethereum too)

### CODE REVIEW

**Comment by ukstv** [comment]
Hey @zachferland @oed Finally this does it all right. One change in the next couple of weeks expected is to bump version of `@glif` packages from beta to prod. Otherwise, good to go.

**Review by oed — APPROVED** [review]
Looks good 👍

**Comment by oed** [comment]
This is now released as `3id-blockchain-utils@1.1.0` 🎉

**Comment by ukstv** [comment]
Hooray!

**Pull request merged**
